# src/main/resources/application.yml
server:
  port: 1236
spring:
  application:
    name: memory-service

  datasource:
    url: jdbc:postgresql://localhost:5432/memory_service_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver


  ai:
    zhipuai:
      api-key: #你的apikey
      chat:
        options:
          model: glm-4
          temperature: 0.2 # 分析任务，温度低一些保证稳定
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true


logging:
  level:
    com.example.memoryservice: DEBUG
    com.example.memoryservice.mapper: TRACE
management:
  endpoints:
    web:
      exposure:
        include: health,info,trace,metrics
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans