server:
  port: 1242

spring:
  application:
    name: vision-analysis-service
zhipu:
  api:
    key:  #  API Key
  model:
    vision: glm-4.1v-thinking-flashx # ??????????
management:
  endpoints:
    web:
      exposure:
        include: health,info,trace,metrics
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans