server:
  port: 1242

spring:
  application:
    name: vision-analysis-service
# ??????????AI SDK
zhipu:
  api:
    key: 18dc85f52e194ee78697a8ad87b22871.nPsJDtsyetDaaj5O # ?? ????????? API Key
  model:
    vision: glm-4.1v-thinking-flashx # ??????????