spring:
  application:
    name: ai-chat-service
  config:
    import: "optional:classpath:persona.yml"
  ai:
    zhipuai:
      api-key: #你的apikey
      chat:
        options:
          model: glm-4
  data:
    mongodb:
      uri: mongodb://root:SAPiece%40zll9@localhost:27017/ai_dynamic_personality_service?authSource=admin
server:
  port: 1235
management:
  endpoints:
    web:
      exposure:
        include: health,info,trace,metrics
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

