server:
  port: 1239
spring:
  application:
    name: emotion-analysis-service
  ai:
    zhipuai:
      api-key: 18dc85f52e194ee78697a8ad87b22871.nPsJDtsyetDaaj5O
      chat:
        options:
          model: glm-4
          temperature: 0.1
management:
  endpoints:
    web:
      exposure:
        include: health,info,trace,metrics
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans