server:
  port: 1240

spring:
  application:
    name: feedback-service
  datasource:
    url: jdbc:postgresql://localhost:5432/feedback_service_db
    username: admin
    password: admin

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,trace,metrics
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans